---
name: CI Pipeline

on:
  push:
    branches: [ main, clusternet ]
  pull_request:
    branches: [ main, clusternet ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.0'

    - name: Building binary
      run: |
        go build -a -o build/_output/bin/multicluster-operators-placementrule ./cmd/manager
        go build -a -o build/_output/bin/gitopscluster ./cmd/gitopscluster

    - name: Set up QEMU
      if: github.event_name != 'pull_request'
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      if: github.event_name != 'pull_request'
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm
        file: ./build/Dockerfile
        push: true
        tags: quay.io/danielxlee/multicluster-operators-placementrule:latest
